[add]db,models
lit-kansai/dj_system-api pull request #18
Opened 2021-12-21 01:06 UTC by konnyakuken

作成したER図を元にDBとmodelファイルを作りました。
modelの関連付けが少し怪しいので、見ていただけるとありがたいです。
Closes #1

2021-12-21 15:24 UTC, mizucoffee requested changes
@konnyakuken PRありがとうございます！
レビューしたので確認お願いします！

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216042843_create_user.rb
> +      t.datetime :create_at
過去形

あと、created_at, updated_atを作るときは `t.timestamps null: false` がおすすめ。勝手によしなにやってくれる。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216044448_create_accesstoken.rb
> +    create_table :AccessTokens do |t|
テーブル名はスネークケース。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216154137_create_letter.rb
> +    create_table :Letters do |t|
テーブル名はスネークケース。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216154326_create_song.rb
> +      create_table :Songs do |t|
テーブル名はスネークケース。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216155119_create_room.rb
> +      create_table :Rooms do |t|
テーブル名はスネークケース。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216155420_create_roomuser.rb
> +    create_table :RoomUsers do |t|
テーブル名はスネークケース。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216154137_create_letter.rb
> +      t.datetime :create_at
過去形

あと、created_at, updated_atを作るときは `t.timestamps null: false` がおすすめ。勝手によしなにやってくれる。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216155119_create_room.rb
> +        t.datetime :create_at
過去形

あと、created_at, updated_atを作るときは `t.timestamps null: false` がおすすめ。勝手によしなにやってくれる。

2021-12-21 15:24 UTC, mizucoffee commented on models/dj_system-api.rb
> +    has_many :AccessTokens
スネークケース

2021-12-21 15:24 UTC, mizucoffee commented on models/dj_system-api.rb
> +    belongs_to :Room
スネークケース

2021-12-21 15:24 UTC, mizucoffee commented on models/dj_system-api.rb
> +    belongs_to :User
スネークケース

2021-12-21 15:24 UTC, mizucoffee commented on models/dj_system-api.rb
> +    belongs_to :Letter
スネークケース

2021-12-21 15:24 UTC, mizucoffee commented on models/dj_system-api.rb
> +    has_many :Songs
スネークケース

2021-12-21 15:24 UTC, mizucoffee commented on models/dj_system-api.rb
> +    belongs_to :User
スネークケース

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216044448_create_accesstoken.rb
> +class CreateAccesstoken < ActiveRecord::Migration[6.1]
`AccessToken` にしたい！

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216044448_create_accesstoken.rb
> +      t.string :refresh_token
目的無いけど一応`t.timestamps null: false`作っておこう。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216154326_create_song.rb
> +        t.string :song_id
目的無いけど一応`t.timestamps null: false`作っておこう。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216155420_create_roomuser.rb
> +      t.integer :room_id
目的無いけど一応`t.timestamps null: false`作っておこう。

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216042843_create_user.rb
> +class CreateUser < ActiveRecord::Migration[6.1]
ファイル名、クラス名は一応複数形が正しい...
`xxx_create_users.rb` `CreateUsers`

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216044448_create_accesstoken.rb
> +class CreateAccesstoken < ActiveRecord::Migration[6.1]
ファイル名、クラス名は一応複数形が正しい...

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216154137_create_letter.rb
> +class CreateLetter < ActiveRecord::Migration[6.1]
ファイル名、クラス名は一応複数形が正しい...

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216154326_create_song.rb
> +class CreateSong < ActiveRecord::Migration[6.1]
ファイル名、クラス名は一応複数形が正しい...

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216155119_create_room.rb
> +class CreateRoom < ActiveRecord::Migration[6.1]
ファイル名、クラス名は一応複数形が正しい...

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216155420_create_roomuser.rb
> +class CreateRoomuser < ActiveRecord::Migration[6.1]
ファイル名、クラス名は一応複数形が正しい...

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216155420_create_roomuser.rb
> +class CreateRoomuser < ActiveRecord::Migration[6.1]
`CreateRoomUsers`にしたい！

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216154137_create_letter.rb
> +      t.string :room_id
よく考えたらnumberで良さそう

2021-12-21 15:24 UTC, mizucoffee commented on db/migrate/20211216155119_create_room.rb
> +        t.string :playkist_id
typo
`playlist_id`

2021-12-21 15:24 UTC, mizucoffee commented on models/dj_system-api.rb
> +    has_many :Rooms
メインのRoomと自分が管理しているRoomの名前がかぶってるので別名にする必要がある
`has_many :my_rooms, class_name: "Room", foreign_key: "id"`
みたいな感じで行けないかなあ。

2021-12-21 15:30 UTC, mizucoffee commented on db/migrate/20211216042843_create_user.rb
> +      t.datetime :create_at
6行目の話し

2021-12-21 15:30 UTC, mizucoffee commented on db/migrate/20211216044448_create_accesstoken.rb
> +    create_table :AccessTokens do |t|
3行目の話

2021-12-21 15:30 UTC, mizucoffee commented on db/migrate/20211216154137_create_letter.rb
> +    create_table :Letters do |t|
3行目の話

2021-12-21 15:31 UTC, mizucoffee commented
何行目かがうまく参照出来てない所があるので分からなかったら聞いて下さい〜

2021-12-30 18:52 UTC, konnyakuken commented
@mizucoffee 
レビューされたものを全部修正したので、確認お願いします！

2021-12-31 08:14 UTC, mizucoffee reviewed
@konnyakuken 概ね良いかと思います！
細かい所だけ修正してマージしますねー。

2021-12-31 08:14 UTC, mizucoffee commented on db/migrate/20211230181154_accesstokens.rb
> +class Accesstokens < ActiveRecord::Migration[6.1]
`CreateAccess"T"okens`にしたいっていう意味だった...わかりづらくて申し訳ない。
こちらで修正しておきますー。

2021-12-31 08:15 UTC, mizucoffee approved these changes

2021-12-31 08:18 UTC, merged