get room's letters
lit-kansai/dj_system-api pull request #61
Opened 2022-07-06 02:56 UTC by 9-sho-5

2022-07-06 02:57 UTC, 9-sho-5 commented
@mizucoffee 
チェックお願いします！

2022-07-11 16:14 UTC, mizucoffee requested changes

2022-07-11 16:14 UTC, mizucoffee commented on app.rb
> +    letters = roome.letters
typoしてそうです！

2022-07-11 16:14 UTC, mizucoffee commented on app.rb
> +    room = @user.rooms.find_by(id: params[:id])
find_byは該当するレコードが見つからなかった時にnilを返すので、その後の `room.letters` で落ちそうです。
roomがnilだった時点で404を返すようにしたいです！

2022-07-20 04:47 UTC, closed without merging